### ISSUE TITLE
Colour defaulting when changing value

### ISSUE THREAD

**Issue by asm512** [LfxB/DriveModes#1]
As you can see in the [this video](https://youtu.be/R_L3RVWcKFs) the vehicle colour defaults to black when changing a value and I don't have the time to inspect the code at the moment.

**Comment by LfxB** [comment]
There doesn't seem to be any error in [the code](https://github.com/LfxB/DriveModes/blob/master/DriveModes2.0Onwards/DriveModes.cs#L2021) that transfers the colour from the existing vehicle to the clone vehicle.
Suspect lines: 2021-2028, 2161-2168.
[Line 1098](https://github.com/LfxB/DriveModes/blob/master/DriveModes2.0Onwards/DriveModes.cs#L1098) is what is executed after changing a value.

Are you on GTA V version 1.0.1290.1? I am still on the previous update.
Does this happen with all vehicles?

**Comment by asm512** [comment]
Indeed, from first glance the code looks fine. Latest version, let me test on other vehicles

**Comment by asm512** [comment]
Strange, works for all other vehicles tested (3 vanilla and 3 custom)

**Comment by peaches6** [comment]
I'll go ahead and close this since logically there shouldn't be an error and it only happens on select vehicles.

**Comment by asm512** [comment]
I'll go ahead and close this since logically there shouldn't be an error and it only happens on select vehicles.
